### ISSUE TITLE
Help me gather info! Free Dev Swag!

### ISSUE THREAD

**Issue by Joonsang1994** [Joonsang1994/free-tshirts-stickers-and-swag-for-developers#12]
I'm curating a list of free items (like hacktoberfest!) available to developers. [Check it out ](https://github.com/Joonsang1994/free-tshirts-stickers-and-swag-for-developers).

If you have knowledge of any such giveaways please raise a pull request along with the link. I'll be very happy to add that to the existing list :smiley:

**Comment by KartSriv** [comment]
@Joonsang1994 I have created an issue on swag-for-dev about FSFE swag. I personally got it delivered to India and you can check it out in https://github.com/swapagarwal/swag-for-dev/issues/271
