### ISSUE TITLE
Are you looking for any collaborator?

### ISSUE THREAD

**Issue by KartSriv** [Joonsang1994/free-tshirts-stickers-and-swag-for-developers#18]
Are you looking for any collaborator? If "yes" then I could help. I am most of the time sitting in front of GitHub and will be mostly active. I can accept PRs very quickly and will fix any markdown related issues in a jiffy. I am volunteering because this repo addresses issues and PRs faster than others (swag-for dev for example). If you gather more collaborators then this repo will stay fresh as always.

Thanks, @KartSriv

**Comment by Joonsang1994** [comment]
Hey! That would be great, I've sent you the invite for the same.

**Comment by KartSriv** [comment]
Thanks, @Joonsang1994! Will do my best to make this repo better. Also will be updating you with all the changes I'll be postulating via a PR even though I am a contributor. Let this issue be open so we can give way for more people to collaborate. Once again, Thank you for making me a contributor!
