### ISSUE TITLE
Can we create a GitHub Page for free-tshirts-stickers-and-swag-for-developers?

### ISSUE THREAD

**Issue by KartSriv** [Joonsang1994/free-tshirts-stickers-and-swag-for-developers#20]
Hey, @Joonsang1994! I got an idea. **Why don't we create a GitHub Page for this repo?** _I can show you a personal example:_ **https://karthiksrivijay.me/ArduinoSnippets.html**.  ArduinoSnippets.html redirects to https://kartsriv.github.io/Arduino-Snippets/ which is a GitHub Page. It took 5-10 minutes to create it and it's quite cool. It just displays the README.md of a repo. If you like this idea then I can assign myself. You can even create your own webpage and host it via GitHub like I've done with my personal website but it takes a lot of manpower and time which I guess we both don't have. What are you're thoughts?

**Comment by KartSriv** [comment]
Since I am just a collaborator. I can't create a GitHub page for this but if you want I can show you an example by forking this repo.

**Comment by KartSriv** [comment]
Check this out: https://kartsriv.github.io/free-tshirts-stickers-and-swag-for-developers/

I've just created a GitHub Page for my old fork. 
**THIS IS NOT THE FINAL PRODUCT AND THE FINAL PRODUCT WILL BE IN joonsang1994.github.io**

**Comment by KartSriv** [comment]
Shit! I just remembered. GitHub Pages are only available for Pro Users and it seems like you're not one. I don't think it's right to host this website under my name because almost all the credits goes to you. I think we can create an Organization and I can share my Pro Tier to all the users in this organization and because of this even you can become a Pro user, I guess.

**Comment by KartSriv** [comment]
@Joonsang1994

**Comment by KartSriv** [comment]
@Joonsang1994

**Comment by KartSriv** [comment]
@Joonsang1994 Shall we create an Organization for this repo?

**Comment by Joonsang1994** [comment]
@KartSriv I don't think a GitHub pages website is required. I wanted it to be a simple list and let it be that way. Going forward we'll consider it.

**Comment by KartSriv** [comment]
@Joonsang1994 We all know Repositories don't come before in Search Results. So many people won't be able to see this repo. We can configure the SEO for our GitHub Page which will attract more people.

A Website attracts programmers who don't use GitHub, Non-Programmers, Newbies, etc...

**Comment by KartSriv** [comment]
@Joonsang1994 I can easily create a website under your username. If you agree to it and you'll also get GitHub Pro.

**Comment by KartSriv** [comment]
@Joonsang1994

**Comment by KartSriv** [comment]
@Joonsang1994

**Comment by KartSriv** [comment]
@Joonsang1994 Any thoughts?

**Comment by KartSriv** [comment]
@Joonsang1994 What happened to you? Have you abandoned this repo?
