### ISSUE TITLE
Tested feature enhancement

### ISSUE THREAD

**Issue by Joonsang1994** [Joonsang1994/free-tshirts-stickers-and-swag-for-developers#22]
The "Tested" text written after each swag is a bit too distracting.
 I think something like :heavy_check_mark:  or :white_check_mark: will be better. It will be short and will convey the message. What do you think?

**Comment by KartSriv** [comment]
Just fixed in cb4655614ab606db8e096d700f2e8d24fa76c4ea

**Comment by KartSriv** [comment]
I didn't create a PR cause this edit was quite straight forward.
