### ISSUE TITLE
@Joonsang1994 Are you still alive?

### ISSUE THREAD

**Issue by KartSriv** [Joonsang1994/free-tshirts-stickers-and-swag-for-developers#23]
**@Joonsang1994 If you're alive then please close this issue.**

**Comment by undrline** [comment]
I think this is the first I'm I've ever wanted to use roflmao.  That can't be original, but it's the first time I've seen it.  Shame if tragedy really did strike ...

**Comment by KartSriv** [comment]
**ROFLMAO** xD He didn't respond to any of my comments in https://github.com/Joonsang1994/free-tshirts-stickers-and-swag-for-developers/issues/20. It's almost a month and I am kinda worried.

**Comment by KartSriv** [comment]
@Joonsang1994 The last time you responded was on May 24th and now it's July 24. You've been away for exactly 2 months.

**Comment by Joonsang1994** [comment]
Lol. I really forgot I had a Github account.

**Comment by KartSriv** [comment]
LMAO, Dude XD 
Glad to hear from you. I am currently AFK and most of my friends presume I am dead. 
Anyways, Get Going Pal
