### ISSUE TITLE
Expired Swags

### ISSUE THREAD

**Issue by SayanBan** [Joonsang1994/free-tshirts-stickers-and-swag-for-developers#26]
1. DigitalOcean Stickers Swags have expired. They don't provide those swags anymore.

2. New Exclusive Bottle for amazon Alexa Hindi Developers, i.e, those who will publish their skills in Hindi to the Indian store.

![New Swag for Hindi Developers](https://m.media-amazon.com/images/G/01/mobile-apps/dex/alexa/alexa-skills-kit/india/INIncentives201907V2._CB442378486_.png)

**Comment by KartSriv** [comment]
Thanks a lot @SayanBan! All the issues you've mention have been resolved. Once again, Thank you so much for spending your valuable time on identifying these issues!
